---
# CentOS specific package installations
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: fetch EPEL repository
  yum: name=http://mirror.pnl.gov/epel/6/i386/epel-release-6-8.noarch.rpm

- name: install packages
  yum: name="{{ item }}" state=present
  with_items: packages

- name: enable httpd
  service: name={{ item }} enabled=yes state=started
  with_items:
  - "{{ apache_service }}"
